"------------------------vundle管理所有的插件begin--------------------------
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"Plugin 'VundleVim/Vundle.vim'
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'

Plugin 'Valloric/YouCompleteMe'

Plugin 'vim-scripts/taglist.vim'

"Plugin 'Lokaltog/vim-powerline.git'
"Plugin 'Lokaltog/powerline-fonts.git'

Plugin 'vim-scripts/c.vim'

"Plugin 'vim-scripts/cscope_plus.vim'
Plugin 'vim-scripts/JumpInCode-new-update'
"Plugin 'vim-scripts/JumpInCode'

Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'

Plugin 'L9'


"自动补全括号
Plugin 'jiangmiao/auto-pairs.git'

call vundle#end()
filetype plugin indent on
"------------------------vundle管理所有的插件end--------------------------

"NERDTree {
map <F10> :NERDTreeToggle<CR>
""autocmd VimEnter * NERDTree
let NERDTreeWinPos="right"
let NERDTreeShowBookmarks=1
"let NERDTreeWinSize=20
"}

"Tlist {
map <F2> :TlistToggle<CR>
""autocm VimEnter * TlistToggle
"let Tlist_WinWidth=30
"}

"StatusLine{{{
set ruler
set laststatus=2
set statusline+=%F%m%r%h%w\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]\ %{strftime(\"%d/%m/%y-%H:%M\")} 
"set guifont=PowerlineSymbols\ for\ Powerline
"set t_Co=256
"set noshowmode
"let g:Powerline_symbols='fancy'
"let Powerline_symbols='compatible'
"}}}

"other {{{
syntax on
set autoindent
set autoread
set autowrite
set smartindent                 " smart autoindenting when starting a new line
set nobackup                    " keep a backup file
set backspace=indent,eol,start  " backspacing over everything in insert mode
set listchars=tab:>.,eol:\$     " strings to use in 'list' mode
set popt=left:8pc,right:3pc     " print options
set hlsearch                    " highlight the last used search pattern
set incsearch                   " do incremental searching
set showcmd                     " display incomplete commands
set visualbell                  " visual bell instead of beeping
set number
set nowrap
set softtabstop=8
set shiftwidth=8
set tabstop=8
set expandtab
"}}}

